version: '3'

services:

  web:
    environment:
      - FLASK_APP=app/app
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    build:
        context: .
    ports:
        - 5000:5000
    volumes: [".:/app"]
    command: ["flask", "run", "--host=0.0.0.0"]
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=todo_db

    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
