version: "3.5"
services:
  server: &server
    build: .
    ports: ['5000:5000']
    volumes: ['.:/usr/src/app']
    restart: always
    environment:
      ENV: dev
      FLASK_APP: "app/app:app"
    command: "python -m flask run --host=0.0.0.0 -p 5000"

    depends_on:
      - redis

  redis:
    image: redis

  test:
    <<: *server
    ports: ['5000:5000']
    volumes: ['.:/usr/src/app']
    command: docker/run_tests.sh
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    environment:
      ENV: test
