version: "3.5"
services:
  server: &server
    container_name: fast-api
    build: .
    ports: ['8000:8000']
    volumes: ['.:/usr/src/app']
    restart: always
    environment:
      ENV: dev
      # DB_USERNAME: sa
      # DB_PASSWORD: password
      # DB_DATABASE: todo_db
      # DB_HOST: localhost
    command: "python -m uvicorn app.app:app --reload --host '0.0.0.0' --port 8000"
    networks:
      - todo

  test:
    <<: *server
    ports: ['5000:5000']
    volumes: ['.:/usr/src/app']
    command: docker/run_tests.sh
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    environment:
      ENV: test



networks:
  todo:

