version: "3"
services:
  server:
    container_name: flask
    build: .
    ports: ['5000:5000']
    volumes: ['.:/usr/src/app']
    restart: always
    environment:
      ENV: DEVELOPMENT
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_DATABASE: database_name
      DB_HOST: localhost
    links:
      - database

  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: database_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    expose:
      - '3306'
    volumes:
      - flask-db:/var/lib/mysql
    links:
      - sqlpad

  sqlpad:
    image: sqlpad
    hostname: 'sqlpad'
    ports:
      - '3000:3000'
    environment:
      - SQLPAD_DEBUG=TRUE
    volumes:
      - sqlpad-volume:/var/lib/sqlpad
volumes:
  flask-db:
  sqlpad-volume:
