version: '3'

services:

  web:
    environment:
      - FLASK_APP=app/app
      - FLASK_ENV=development
    build:
        context: .
    ports:
        - 5000:5000
    volumes: [".:/app"]
    command: ["flask", "run", "--host=0.0.0.0"]
