version: "3.5"
services:
  server: &server
    container_name: flask
    build: .
    ports: ['5000:5000']
    volumes: ['.:/usr/src/app']
    restart: always
    environment:
      ENV: DEVELOPMENT
      # DB_USERNAME: sa
      # DB_PASSWORD: password
      # DB_DATABASE: todo_db
      # DB_HOST: localhost
    links:
      - db
    networks:
      - todo-api

  test:
    <<: *server
    ports: ['5000:5000']
    volumes: ['.:/usr/src/app']
    command: docker/run_tests.sh --format-code
    environment:
      ENV: TEST
    stdin_open: true
    tty: true

  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    expose:
      - '3306'
    depends_on:
      - sqlpad
    networks:
      - todo-api


  sqlpad:
    image: "sqlpad/sqlpad"
    ports:
      - 3000:3000
    environment:
      SQLPAD_ADMIN: admin
      SQLPAD_ADMIN_PASSWORD: password
      SQLPAD_DEBUG: "true"
      SQLPAD_CONNECTIONS__todo__name: "TODO DB"
      SQLPAD_CONNECTIONS__todo__driver: postgres
      SQLPAD_CONNECTIONS__todo__host: db
      SQLPAD_CONNECTIONS__todo__port: 5432
      SQLPAD_CONNECTIONS__todo__database: todo_db
      SQLPAD_CONNECTIONS__todo__username: sa
      SQLPAD_CONNECTIONS__todo__password: password
    networks:
      - todo-api

networks:
  todo-api:
    name: todo-api
