name: Test CI
on: push
jobs:
    test_job:
        name: Test jobs
        runs-on: ubuntu-latest
        steps:
            - name: Print a greeting
              run:  |
                echo Hello there!