name: Test
on: push
jobs:
    run-tests:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
          - name: Check out code
            uses: actions/checkout@v1
          - name: Run Tests
            run: docker-compose run test